### ISSUE TITLE
The tcdb doesn't seem to work

### ISSUE THREAD

**Issue by hyhkjiy** [flyskywhy/tc32#1]
System Infomation:
---
macOS Monterey
version 12.0.1
MacBook Pro (Retina, 13-inch, Early 2015)

Steps
---
I use usb to connect Telink EVK to my Apple computer, then use usb to connect EVK and TLSR8258 development board and use an extra cable to connect SWM and SWS ports.

When I enter tcdb rst on the command line, nothing happens except for the prompt "ERR: Slave MCU Reset Failed".

When I enter ‘tcdb -b -m -e -i out/8258_ble_sample.bin’ in the command line, it prompts ‘EVK: No Swire Slave Device’ and the LED on the EVK flashes.

![image](https://user-images.githubusercontent.com/18144117/144265229-dc48ed4e-faa3-4755-b1d4-d1e4a45e0d80.png)

I don't know why it fails, can someone solve it? Or provide another way to download firmware on macos, I would very appreciate.

**Comment by flyskywhy** [comment]
I can compile firmware on every platform, but only debug with EVK on Windows, maybe you can try it too, or ask Telink company for help.
